
package com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleInterestImplService", targetNamespace = "http://example.com/", wsdlLocation = "http://localhost:8080/SimpleInterest?wsdl")
public class SimpleInterestImplService
    extends Service
{

    private final static URL SIMPLEINTERESTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLEINTERESTIMPLSERVICE_EXCEPTION;
    private final static QName SIMPLEINTERESTIMPLSERVICE_QNAME = new QName("http://example.com/", "SimpleInterestImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SimpleInterest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLEINTERESTIMPLSERVICE_WSDL_LOCATION = url;
        SIMPLEINTERESTIMPLSERVICE_EXCEPTION = e;
    }

    public SimpleInterestImplService() {
        super(__getWsdlLocation(), SIMPLEINTERESTIMPLSERVICE_QNAME);
    }

    public SimpleInterestImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLEINTERESTIMPLSERVICE_QNAME, features);
    }

    public SimpleInterestImplService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLEINTERESTIMPLSERVICE_QNAME);
    }

    public SimpleInterestImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLEINTERESTIMPLSERVICE_QNAME, features);
    }

    public SimpleInterestImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleInterestImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleInterestSEI
     */
    @WebEndpoint(name = "SimpleInterestImplPort")
    public SimpleInterestSEI getSimpleInterestImplPort() {
        return super.getPort(new QName("http://example.com/", "SimpleInterestImplPort"), SimpleInterestSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleInterestSEI
     */
    @WebEndpoint(name = "SimpleInterestImplPort")
    public SimpleInterestSEI getSimpleInterestImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/", "SimpleInterestImplPort"), SimpleInterestSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLEINTERESTIMPLSERVICE_EXCEPTION!= null) {
            throw SIMPLEINTERESTIMPLSERVICE_EXCEPTION;
        }
        return SIMPLEINTERESTIMPLSERVICE_WSDL_LOCATION;
    }

}
