
package com.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimpleInterestSEI", targetNamespace = "http://example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimpleInterestSEI {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateSimpleInterest", targetNamespace = "http://example.com/", className = "com.example.client.CalculateSimpleInterest")
    @ResponseWrapper(localName = "calculateSimpleInterestResponse", targetNamespace = "http://example.com/", className = "com.example.client.CalculateSimpleInterestResponse")
    @Action(input = "http://example.com/SimpleInterestSEI/calculateSimpleInterestRequest", output = "http://example.com/SimpleInterestSEI/calculateSimpleInterestResponse")
    public double calculateSimpleInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
